export const CREATE_PAYMENT_LINK_REQUEST = "CREATE_PAYMENT_LINK_REQUEST";
export const CREATE_PAYMENT_LINK_SUCCESS = "CREATE_PAYMENT_LINK_SUCCESS";
export const CREATE_PAYMENT_LINK_FAILURE = "CREATE_PAYMENT_LINK_FAILURE";